### ISSUE TITLE
Show contact names on pending Escrow notification and list

### ISSUE THREAD

**Issue by gnardini** [celo-org/wallet#287]
### Expected Behavior

When a user invites someone they can see the name of the person they invited on a notification on top of the feed and in the list of pending invites.

### Current Behavior

All names show up as Unknown

**Comment by Celoqa** [comment]
Hi @gnardini We have verified this issue on  Android internal build V1.13.0 (1004294348) & TestFlight build V1.13.0 (55) and observe the following.
- **Invited Unknown** is shown instead of username when user send invite to friend who was in their contact list.

**Device:**  iPhone 6+(12.4.5), Samsung Galaxy A31(10).

**Comment by gnardini** [comment]
Hi @Celoqa this hasn't been merged yet and is not part of the 1.13 build!

**Comment by Celoqa** [comment]
Hi @gnardini thanks for the information.
FYI: we have already filed the same issue in the past https://github.com/celo-org/celo-monorepo/issues/2607#issue-557455085
